services:
  news-aggregator:
    build:
      context: .
      dockerfile: Dockerfile  # Optional if named Dockerfile
    image: news-aggregator:01
    container_name: news-aggregator
    restart: always
    ports:
      - "8086:80"
    volumes:
      - /var/www/html/news-aggregator:/home/innoscripta/public_html/news-aggregator
    entrypoint: ["/docker-entrypoint.sh"]
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: news_db
      DB_USERNAME: root
      DB_PASSWORD: Innoscripta

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Innoscripta
      MYSQL_DATABASE: news_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
